# Generated by Django 3.2 on 2022-11-24 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_app', '0002_auto_20221124_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='createdby',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
