# Generated by Django 3.2 on 2022-11-26 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_ebook_createdby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='favourite',
        ),
    ]
