# Generated by Django 3.2 on 2022-11-26 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0006_alter_rating_ebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='review',
        ),
    ]
